apiVersion: v1
kind: Pod
metadata:
  name: affi-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
                - "multinode-demo-m02"
  containers:
    - name: python-app
      image: docker.io/creatorp/python-app
      imagePullPolicy: IfNotPresent
