apiVersion: v1
kind: Service
metadata:
  name: test-python-app
spec:
  selector:
    app: test-python-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-python-app
  template:
    metadata:
      labels:
        app: test-python-app
    spec:
      containers:
        - name: python-app
          image: docker.io/creatorp/python-app:latest
          ports:
            - containerPort: 8080
