apiVersion: v1
kind: Pod
metadata:
  name: test-py
  labels:
    env: test
spec:
  containers:
    - name: python-app
      image: docker.io/creatorp/python-app:latest
      imagePullPolicy: IfNotPresent
  tolerations:
    - key: "kubernetes.io/hostname"
      operator: "Exists"
      effect: "NoSchedule"

